FROM golang:1.20 as builder
WORKDIR /app
COPY . /app
RUN CGO_ENABLED=0 GOOS=linux go build -o main .

FROM gcr.io/distroless/base-debian12:latest
COPY --from=builder /app/main /
EXPOSE 443
CMD ["/main"]
