GET http://localhost:9090/secret_page
Cookie: session=MTY5NzY5NDk2OXxEdi1CQkFFQ180SUFBUkFCRUFBQVBQLUNBQUlHYzNSeWFXNW5EQXNBQ1d4dloyZGxaRjlwYmdSaWIyOXNBZ0lBQVFaemRISnBibWNNQ1FBSGRYTmxjbDlwWkFSMWFXNTBCZ0lBQVE9PXzxijywG6OQF3SXLrcEISLP74P4Cp0tnAFKYB8-zPyigQ==
