GET http://localhost:9090/secure_page
Cookie: session=MTY5NzYxMjM5N3xEdi1CQkFFQ180SUFBUkFCRUFBQVJQLUNBQUlHYzNSeWFXNW5EQXNBQ1d4dloyZGxaRjlwYmdSaWIyOXNBZ0lBQVFaemRISnBibWNNQ1FBSGRYTmxjbDlwWkFaemRISnBibWNNQ0FBR2REUjBjbUYzfKbeFwtqr0H9MlIhHt7V0Bd6eFtOC7neue5I81S0Tr-6
