GET http://localhost:9090/secure_page
Cookie: session=MTY5NzY3NjY5MHxEdi1CQkFFQ180SUFBUkFCRUFBQVJQLUNBQUlHYzNSeWFXNW5EQXNBQ1d4dloyZGxaRjlwYmdSaWIyOXNBZ0lBQVFaemRISnBibWNNQ1FBSGRYTmxjbDlwWkFaemRISnBibWNNQ0FBR2MyRnRjR3hsfNcQHEeh9gG58VQI4BxfQG07YTBaIcQ_0yR0Ajr9dt8p
