GET http://localhost:9090/secure_page
Cookie: session=MTY5NzYxMzA5NXxEdi1CQkFFQ180SUFBUkFCRUFBQVJQLUNBQUlHYzNSeWFXNW5EQXNBQ1d4dloyZGxaRjlwYmdSaWIyOXNBZ0lBQVFaemRISnBibWNNQ1FBSGRYTmxjbDlwWkFaemRISnBibWNNQ0FBR2REUjBjbUYzfP1avN8FAv1tICWTWaEvsmgXt6QrX9HdB5qmmTzcd6pj
