POST http://localhost:9090/posts
Cookie: session=MTcwNjg1NjAzMnxEdi1CQkFFQ180SUFBUkFCRUFBQVBQLUNBQUlHYzNSeWFXNW5EQWtBQjNWelpYSmZhV1FFZFdsdWRBWUNBQUVHYzNSeWFXNW5EQXNBQ1d4dloyZGxaRjlwYmdSaWIyOXNBZ0lBQVE9PXzyQj3oIB9r6GvGgHLmXoOyH3iSAIWkKZS1gDYRlsjhBg==
Content-Type: application/x-www-form-urlencoded

title=テストポスト&body=記事内容&category_id=1
